capstone/app/urls.py
from django.urls import re_path, path
from capstone.app import views
from .API.YelpAPI.yelp import yelp_main, query_api
from .API.MapsAPI.maps import googlecode
from .API.SanjayAPI.nutrinix import nutritioncode
from .API.RobleAPI.nutrition import foodnutritioncode

# SET THE NAMESPACE!
app_name = 'app'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('yelp_main/', yelp_main, name='yelp_main' ),
    path('googlecode/', googlecode, name='googlecode' ),
    path('nutritioncode/', nutritioncode, name='nutritioncode' ),
    path('query_api/', query_api, name='query_api'),
    path('registration/', views.register_request, name='registration'),
    path('foodnutritioncode/', foodnutritioncode, name= 'foodnutritioncode'),
    re_path(r'^user_login/$', views.user_login,name='user_login'),
]

capstone/app/templates/includes/_formhelpers.html
{% macro render_field(field) %}
<dl>
    {{ field.label }}
    <dd>
        {{ field(**kwargs)|safe }}
        {% if field.errors %}
        <ul class=errors>
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </dd>
</dl>
    {% endmacro %}

capstone/app/templates/includes/_messages.html
  {% if messages %}

    {% for message in messages %}
<div class="alert-">{{ message }}</div>
    {% endfor %}

  {% endif %}

{% if error %}
<div class="alert alert-danger">{{error}}</div>
{% endif %}


{% if msg %}
<div class="alert alert-success">{{msg}}</div>
{% endif %}

capstone/app/templates/includes/_navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/home" class="navbar-brand">Jersey Foodie</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/foodie">Foodie</a></li>
                <li><a href="/about">Jersey Foodie</a></li>
                <li><a href="/contact">Contact Us</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="/dashboard">Dashboard</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'app:user_login' %}">Login</a></li>
                <li><a href="{% url 'app:registration' %}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>